version: '3'

services:
  app:
    container_name: skku-ejs-s-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
    stdin_open: true
    tty: true
    environment:
      DEVCONTAINER: 1
      CC: clang
      CCX: clang++